//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Клуб_любителей_скачек
{
    using System;
    using System.Collections.Generic;
    
    public partial class betting
    {
        public int id { get; set; }
        public int horse_id { get; set; }
        public int race_id { get; set; }
        public decimal amount { get; set; }
        public System.DateTime bet_date { get; set; }
        public int member_id { get; set; }
    
        public virtual horse horse { get; set; }
        public virtual members members { get; set; }
        public virtual races races { get; set; }
    }
}
