//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Клуб_любителей_скачек
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;


    
        public partial class RacesclubEntities : DbContext
        {
            private static RacesclubEntities _context;

            public RacesclubEntities()
                : base("name=RacesclubEntities")
            {
            }

            public static RacesclubEntities GetContext()
            {
                if (_context == null)
                    _context = new RacesclubEntities();
                return _context;
            }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                throw new UnintentionalCodeFirstException();
            }

            public virtual DbSet<betting> betting { get; set; }
            public virtual DbSet<horse> horse { get; set; }
            public virtual DbSet<members> members { get; set; }
            public virtual DbSet<membership> membership { get; set; }
            public virtual DbSet<races> races { get; set; }
            public virtual DbSet<results> results { get; set; }
        }
    }

